project_id = "ycqinuwrlhuxotypqlfh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[edge_runtime]
enabled = true
port = 54329

# Edge Functions - Configurações otimizadas para logs
[functions.cache-manager]
verify_jwt = true

[functions.demo-rate-limit]
verify_jwt = false

[functions.executar-auditoria]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.marketplace-auth]
verify_jwt = true

[functions.production-health]
verify_jwt = true

[functions.production-metrics]
verify_jwt = true

[functions.prompt-generator]
verify_jwt = true

[functions.code-applier]
verify_jwt = true

[functions.rollback-version]
verify_jwt = true

[functions.create-sla-acceptance]
verify_jwt = true

[functions.test-nfe-connection]
verify_jwt = true

[functions.compression-proxy]
verify_jwt = false

[functions.health-check]
verify_jwt = false

# New AI functions
[functions.gpt-pipeline-chat]
verify_jwt = false

[functions.save-knowledge]
verify_jwt = true
