
import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Building,
  Warehouse,
  DollarSign,
  FileText,
  Cog,
  BarChart3,
  Wrench,
  Shield,
  Store,
  Link
} from 'lucide-react';
import type { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/app',
    href: '/app',
    icon: LayoutDashboard,
    order: 1,
  },
  {
    id: 'vendas',
    title: 'Vendas',
    path: '/app/vendas',
    href: '/app/vendas',
    icon: ShoppingCart,
    order: 2,
  },
  {
    id: 'produtos',
    title: 'Produtos',
    path: '/app/produtos',
    href: '/app/produtos',
    icon: Package,
    order: 3,
  },
  {
    id: 'clientes',
    title: 'Clientes',
    path: '/app/clientes',
    href: '/app/clientes',
    icon: Users,
    order: 4,
  },
  {
    id: 'compras',
    title: 'Compras',
    path: '/app/compras',
    href: '/app/compras',
    icon: Building,
    order: 5,
  },
  {
    id: 'estoque',
    title: 'Estoque',
    path: '/app/estoque',
    href: '/app/estoque',
    icon: Warehouse,
    order: 6,
  },
  {
    id: 'financeiro',
    title: 'Financeiro',
    path: '/app/financeiro',
    href: '/app/financeiro',
    icon: DollarSign,
    order: 7,
  },
  {
    id: 'notas_fiscais',
    title: 'Notas Fiscais',
    path: '/app/notas-fiscais',
    href: '/app/notas-fiscais',
    icon: FileText,
    order: 8,
  },
  {
    id: 'producao',
    title: 'Produção',
    path: '/app/producao',
    href: '/app/producao',
    icon: Wrench,
    order: 9,
  },
  {
    id: 'relatorios',
    title: 'Relatórios',
    path: '/app/relatorios',
    href: '/app/relatorios',
    icon: BarChart3,
    order: 10,
  },
  {
    id: 'analytics',
    title: 'Analytics',
    path: '/app/analytics',
    href: '/app/analytics',
    icon: BarChart3,
    order: 11,
  },
  {
    id: 'marketplace_canais',
    title: 'Marketplace',
    path: '/app/marketplace-channels',
    href: '/app/marketplace-channels',
    icon: Store,
    order: 12,
  },
  {
    id: 'integracoes',
    title: 'Integrações',
    path: '/app/integracoes',
    href: '/app/integracoes',
    icon: Link,
    order: 13,
  },
  {
    id: 'configuracoes',
    title: 'Configurações',
    path: '/app/configuracoes',
    href: '/app/configuracoes',
    icon: Cog,
    order: 14,
  },
  {
    id: 'admin',
    title: 'Administração',
    path: '/app/admin',
    href: '/app/admin',
    icon: Shield,
    adminOnly: true,
    order: 15,
    submenu: [
      {
        id: 'admin_usuarios',
        title: 'Usuários',
        path: '/app/admin/usuarios',
        href: '/app/admin/usuarios',
        order: 1,
      },
      {
        id: 'admin_niveis_acesso',
        title: 'Níveis de Acesso',
        path: '/app/admin/niveis-acesso',
        href: '/app/admin/niveis-acesso',
        order: 2,
      },
    ],
  },
];

// Legacy exports for backward compatibility
export const adminMenuItems: Omit<MenuItem, "submenu">[] = [
  {
    id: 'admin_cache',
    title: 'Cache',
    path: '/app/admin/cache',
    href: '/app/admin/cache',
    icon: Shield,
    order: 100,
  },
  {
    id: 'admin_seguranca',
    title: 'Segurança',
    path: '/app/admin/seguranca',
    href: '/app/admin/seguranca',
    icon: Shield,
    order: 101,
  },
];
