
import { 
  LayoutDashboard, 
  ShoppingCart, 
  Package, 
  Users, 
  DollarSign, 
  FileText, 
  BarChart3, 
  Settings, 
  Zap,
  Factory,
  Receipt,
  ShieldCheck,
  Link,
  Webhook,
  Bell,
  ShoppingBag,
  TrendingUp,
  UserCog,
  Shield,
  Database,
  Activity,
  MessageSquare,
  Calendar,
  HardDrive,
  Wrench,
  Gamepad2,
  Search,
  Sparkles
} from 'lucide-react';

export const menuItems = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/app/dashboard',
    href: '/app/dashboard',
    icon: LayoutDashboard,
    order: 1,
    submenu: [],
  },
  {
    id: 'comercial',
    title: 'Comercial',
    path: '/app/comercial',
    href: '/app/comercial',
    icon: ShoppingCart,
    order: 2,
    submenu: [
      {
        id: 'vendas',
        title: 'Vendas',
        path: '/app/vendas',
        href: '/app/vendas',
        order: 1,
      },
      {
        id: 'produtos',
        title: 'Produtos',
        path: '/app/produtos',
        href: '/app/produtos',
        order: 2,
      },
      {
        id: 'clientes',
        title: 'Clientes',
        path: '/app/clientes',
        href: '/app/clientes',
        order: 3,
      },
      {
        id: 'compras',
        title: 'Compras',
        path: '/app/compras',
        href: '/app/compras',
        order: 4,
      },
    ],
  },
  {
    id: 'financeiro',
    title: 'Financeiro',
    path: '/app/financeiro',
    href: '/app/financeiro',
    icon: DollarSign,
    order: 3,
    submenu: [],
  },
  {
    id: 'fiscal',
    title: 'Fiscal',
    path: '/app/fiscal',
    href: '/app/fiscal',
    icon: FileText,
    order: 4,
    submenu: [
      {
        id: 'notas-fiscais',
        title: 'Notas Fiscais',
        path: '/app/notas-fiscais',
        href: '/app/notas-fiscais',
        order: 1,
      },
      {
        id: 'configuracao-nfe',
        title: 'Configuração NFe',
        path: '/app/configuracao-nfe',
        href: '/app/configuracao-nfe',
        order: 2,
      },
    ],
  },
  {
    id: 'operacional',
    title: 'Operacional',
    path: '/app/operacional',
    href: '/app/operacional',
    icon: Factory,
    order: 5,
    submenu: [
      {
        id: 'producao',
        title: 'Produção',
        path: '/app/producao',
        href: '/app/producao',
        order: 1,
      },
      {
        id: 'estoque',
        title: 'Estoque',
        path: '/app/estoque',
        href: '/app/estoque',
        order: 2,
      },
    ],
  },
  {
    id: 'relatorios',
    title: 'Relatórios',
    path: '/app/relatorios',
    href: '/app/relatorios',
    icon: BarChart3,
    order: 6,
    submenu: [
      {
        id: 'relatorios-main',
        title: 'Relatórios',
        path: '/app/relatorios',
        href: '/app/relatorios',
        order: 1,
      },
      {
        id: 'analytics',
        title: 'Analytics',
        path: '/app/analytics',
        href: '/app/analytics',
        order: 2,
      },
    ],
  },
  {
    id: 'integracoes',
    title: 'Integrações',
    path: '/app/integracoes',
    href: '/app/integracoes',
    icon: Link,
    order: 7,
    submenu: [
      {
        id: 'marketplace-channels',
        title: 'Canais de Venda',
        path: '/app/marketplace-channels',
        href: '/app/marketplace-channels',
        order: 1,
      },
      {
        id: 'integracoes-main',
        title: 'Integrações',
        path: '/app/integracoes',
        href: '/app/integracoes',
        order: 2,
      },
      {
        id: 'configuracoes-integracoes',
        title: 'Configurações',
        path: '/app/configuracoes-integracoes',
        href: '/app/configuracoes-integracoes',
        order: 3,
      },
    ],
  },
  {
    id: 'notificacoes',
    title: 'Notificações',
    path: '/app/notificacoes',
    href: '/app/notificacoes',
    icon: Bell,
    order: 8,
    submenu: [],
  },
  {
    id: 'configuracoes',
    title: 'Configurações',
    path: '/app/configuracoes',
    href: '/app/configuracoes',
    icon: Settings,
    order: 9,
    submenu: [],
  },
  {
    id: 'administracao',
    title: 'Administração',
    path: '/app/admin',
    href: '/app/admin',
    icon: Shield,
    adminOnly: true,
    order: 10,
    submenu: [
      {
        id: 'admin-panel',
        title: 'Painel Admin',
        path: '/app/admin',
        href: '/app/admin',
        order: 1,
      },
      {
        id: 'admin-audit-logs',
        title: 'Logs de Auditoria',
        path: '/app/admin/audit-logs',
        href: '/app/admin/audit-logs',
        order: 2,
      },
      {
        id: 'admin-integracoes',
        title: 'Integrações',
        path: '/app/admin/integracoes',
        href: '/app/admin/integracoes',
        order: 5,
      },
      {
        id: 'admin-nfe-config',
        title: 'Configuração NFe',
        path: '/app/admin/nfe-config',
        href: '/app/admin/nfe-config',
        order: 6,
      },
      {
        id: 'admin-versions',
        title: 'Versões',
        path: '/app/admin/versions',
        href: '/app/admin/versions',
        order: 7,
      },
      {
        id: 'admin-monitoramento',
        title: 'Monitoramento',
        path: '/app/admin/monitoramento',
        href: '/app/admin/monitoramento',
        order: 8,
      },
      {
        id: 'admin-sla',
        title: 'SLA',
        path: '/app/admin/sla',
        href: '/app/admin/sla',
        order: 9,
      },
      {
        id: 'admin-seguranca-config',
        title: 'Configurações de Segurança',
        path: '/app/admin/seguranca-config',
        href: '/app/admin/seguranca-config',
        order: 10,
      },
      {
        id: 'admin-notificacoes',
        title: 'Notificações',
        path: '/app/admin/notificacoes',
        href: '/app/admin/notificacoes',
        order: 11,
      },
      {
        id: 'admin-backup',
        title: 'Backup',
        path: '/app/admin/backup',
        href: '/app/admin/backup',
        order: 12,
      },
      {
        id: 'admin-cache',
        title: 'Cache',
        path: '/app/admin/cache',
        href: '/app/admin/cache',
        order: 13,
      },
      {
        id: 'admin-compressao',
        title: 'Compressão',
        path: '/app/admin/compressao',
        href: '/app/admin/compressao',
        order: 14,
      },
      {
        id: 'admin-landing-page',
        title: 'Landing Page',
        path: '/app/admin/landing-page',
        href: '/app/admin/landing-page',
        order: 16,
      },
      {
        id: 'admin-auditoria',
        title: 'Auditoria',
        path: '/app/admin/auditoria',
        href: '/app/admin/auditoria',
        order: 17,
      },
    ],
  },
];
