
import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Building,
  Warehouse,
  DollarSign,
  FileText,
  Cog,
  BarChart3,
  Wrench,
  Shield,
  Store,
  Link,
  Database,
  Activity,
  Zap,
  FileTextIcon,
  Globe,
  Bell,
  Settings,
  Package2
} from 'lucide-react';
import type { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/app',
    href: '/app',
    icon: LayoutDashboard,
    order: 1,
    submenu: [],
  },
  {
    id: 'vendas',
    title: 'Vendas',
    path: '/app/vendas',
    href: '/app/vendas',
    icon: ShoppingCart,
    order: 2,
    submenu: [],
  },
  {
    id: 'produtos',
    title: 'Produtos',
    path: '/app/produtos',
    href: '/app/produtos',
    icon: Package,
    order: 3,
    submenu: [],
  },
  {
    id: 'clientes',
    title: 'Clientes',
    path: '/app/clientes',
    href: '/app/clientes',
    icon: Users,
    order: 4,
    submenu: [],
  },
  {
    id: 'compras',
    title: 'Compras',
    path: '/app/compras',
    href: '/app/compras',
    icon: Building,
    order: 5,
    submenu: [],
  },
  {
    id: 'estoque',
    title: 'Estoque',
    path: '/app/estoque',
    href: '/app/estoque',
    icon: Warehouse,
    order: 6,
    submenu: [],
  },
  {
    id: 'financeiro',
    title: 'Financeiro',
    path: '/app/financeiro',
    href: '/app/financeiro',
    icon: DollarSign,
    order: 7,
    submenu: [],
  },
  {
    id: 'notas_fiscais',
    title: 'Notas Fiscais',
    path: '/app/notas-fiscais',
    href: '/app/notas-fiscais',
    icon: FileText,
    order: 8,
    submenu: [],
  },
  {
    id: 'producao',
    title: 'Produção',
    path: '/app/producao',
    href: '/app/producao',
    icon: Wrench,
    order: 9,
    submenu: [],
  },
  {
    id: 'relatorios',
    title: 'Relatórios',
    path: '/app/relatorios',
    href: '/app/relatorios',
    icon: BarChart3,
    order: 10,
    submenu: [],
  },
  {
    id: 'analytics',
    title: 'Analytics',
    path: '/app/analytics',
    href: '/app/analytics',
    icon: BarChart3,
    order: 11,
    submenu: [],
  },
  {
    id: 'marketplace_canais',
    title: 'Marketplace',
    path: '/app/marketplace-channels',
    href: '/app/marketplace-channels',
    icon: Store,
    order: 12,
    submenu: [],
  },
  {
    id: 'integracoes',
    title: 'Integrações',
    path: '/app/integracoes',
    href: '/app/integracoes',
    icon: Link,
    order: 13,
    submenu: [],
  },
  {
    id: 'configuracoes',
    title: 'Configurações',
    path: '/app/configuracoes',
    href: '/app/configuracoes',
    icon: Cog,
    order: 14,
    submenu: [],
  },
  {
    id: 'admin',
    title: 'Administração',
    path: '/app/admin',
    href: '/app/admin',
    icon: Shield,
    adminOnly: true,
    order: 15,
    submenu: [
      {
        id: 'admin_usuarios',
        title: 'Usuários',
        path: '/app/admin/usuarios',
        href: '/app/admin/usuarios',
        order: 1,
      },
      {
        id: 'admin_niveis_acesso',
        title: 'Níveis de Acesso',
        path: '/app/admin/niveis-acesso',
        href: '/app/admin/niveis-acesso',
        order: 2,
      },
      {
        id: 'admin_integracoes',
        title: 'Integrações',
        path: '/app/admin/integracoes',
        href: '/app/admin/integracoes',
        order: 3,
      },
      {
        id: 'admin_notificacoes',
        title: 'Notificações',
        path: '/app/admin/notificacoes',
        href: '/app/admin/notificacoes',
        order: 4,
      },
      {
        id: 'admin_backup',
        title: 'Backup e Restauração',
        path: '/app/admin/backup',
        href: '/app/admin/backup',
        order: 5,
      },
      {
        id: 'admin_cache',
        title: 'Cache',
        path: '/app/admin/cache',
        href: '/app/admin/cache',
        order: 6,
      },
      {
        id: 'admin_compressao',
        title: 'Compressão',
        path: '/app/admin/compressao',
        href: '/app/admin/compressao',
        order: 7,
      },
      {
        id: 'admin_monitoramento',
        title: 'Monitoramento',
        path: '/app/admin/monitoramento',
        href: '/app/admin/monitoramento',
        order: 8,
      },
      {
        id: 'admin_versions',
        title: 'Versões',
        path: '/app/admin/versions',
        href: '/app/admin/versions',
        order: 9,
      },
      {
        id: 'admin_landing_page',
        title: 'Landing Page',
        path: '/app/admin/landing-page',
        href: '/app/admin/landing-page',
        order: 10,
      },
      {
        id: 'admin_seguranca',
        title: 'Segurança',
        path: '/app/admin/seguranca',
        href: '/app/admin/seguranca',
        order: 11,
      },
      {
        id: 'admin_sla',
        title: 'SLA',
        path: '/app/admin/sla',
        href: '/app/admin/sla',
        order: 12,
      },
      {
        id: 'admin_prompt_generator',
        title: 'Painel Técnico',
        path: '/app/admin/prompt-generator',
        href: '/app/admin/prompt-generator',
        order: 13,
      },
    ],
  },
];

// Legacy exports for backward compatibility
export const adminMenuItems: Omit<MenuItem, "submenu">[] = [
  {
    id: 'admin_cache',
    title: 'Cache',
    path: '/app/admin/cache',
    href: '/app/admin/cache',
    icon: Shield,
    order: 100,
  },
  {
    id: 'admin_seguranca',
    title: 'Segurança',
    path: '/app/admin/seguranca',
    href: '/app/admin/seguranca',
    icon: Shield,
    order: 101,
  },
];
