-- Add missing columns to products table for complete ERP functionality
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS product_type text DEFAULT 'produto'::text,
ADD COLUMN IF NOT EXISTS condition text DEFAULT 'novo'::text,
ADD COLUMN IF NOT EXISTS format text DEFAULT 'simples'::text,
ADD COLUMN IF NOT EXISTS unit text,
ADD COLUMN IF NOT EXISTS brand text,
ADD COLUMN IF NOT EXISTS production_type text DEFAULT 'propria'::text,
ADD COLUMN IF NOT EXISTS expiry_date date,
ADD COLUMN IF NOT EXISTS free_shipping boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gross_weight numeric,
ADD COLUMN IF NOT EXISTS height numeric,
ADD COLUMN IF NOT EXISTS width numeric,
ADD COLUMN IF NOT EXISTS depth numeric,
ADD COLUMN IF NOT EXISTS volumes integer DEFAULT 1,
ADD COLUMN IF NOT EXISTS unit_measure text DEFAULT 'cm'::text,
ADD COLUMN IF NOT EXISTS gtin text,
ADD COLUMN IF NOT EXISTS gtin_tax text,
ADD COLUMN IF NOT EXISTS short_description text,
ADD COLUMN IF NOT EXISTS external_link text,
ADD COLUMN IF NOT EXISTS video_link text,
ADD COLUMN IF NOT EXISTS observations text,
ADD COLUMN IF NOT EXISTS crossdocking_days integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS warehouse text,
ADD COLUMN IF NOT EXISTS initial_stock integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS stock_notes text,
ADD COLUMN IF NOT EXISTS suppliers jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS price_list jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS promotional_price numeric,
ADD COLUMN IF NOT EXISTS promotional_date_start date,
ADD COLUMN IF NOT EXISTS promotional_date_end date,
ADD COLUMN IF NOT EXISTS cest_code text,
ADD COLUMN IF NOT EXISTS item_type text,
ADD COLUMN IF NOT EXISTS product_group text,
ADD COLUMN IF NOT EXISTS icms_base numeric,
ADD COLUMN IF NOT EXISTS icms_retention numeric,
ADD COLUMN IF NOT EXISTS tipi_exception text,
ADD COLUMN IF NOT EXISTS pis_fixed_value numeric,
ADD COLUMN IF NOT EXISTS cofins_fixed_value numeric,
ADD COLUMN IF NOT EXISTS estimated_taxes_percentage numeric,
ADD COLUMN IF NOT EXISTS additional_tax_data jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS custom_attributes jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS images jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS main_image_url text,
ADD COLUMN IF NOT EXISTS integration_data jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS external_id text;